import {
  Owostack,
  metered,
  boolean,
  creditSystem,
  creditPack,
  plan,
} from "owostack";
export const sendEmail = metered("send-email", { name: "send-email" });
export const apiRequests = metered("api-requests", { name: "api requests" });
export const sso = boolean("sso", { name: "sso" });
export const thirdpen = metered("thirdpen", { name: "Thirdpen" });
export const dearfutureself = metered("dearfutureself", {
  name: "dearfutureself",
});
export const dfs = metered("dfs", { name: "dfs" });
export const supportCredits = creditSystem("support-credits", {
  name: "support credits",
  features: [dfs(20), apiRequests(10), dearfutureself(1)],
});
export const thirdpenCredits = creditSystem("thirdpen-credits", {
  name: "thirdpen-credits",
  features: [thirdpen(3)],
});
export const owo = new Owostack({
  secretKey: process.env.OWOSTACK_SECRET_KEY!,
  catalog: [
    plan("test3", {
      name: "test3",
      price: 10000,
      currency: "NGN",
      interval: "monthly",
      provider: "paystack",
      features: [
        sendEmail.limit(10, {
          reset: "5min",
          usageModel: "included",
          ratingModel: "volume",
          tiers: [
            { upTo: 30, unitPrice: 0, flatFee: 1000 },
            { upTo: 100, unitPrice: 0, flatFee: 5000 },
          ],
          billingUnits: 1,
          overage: "charge",
        }),
        apiRequests.config({
          limit: null,
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("testesa", {
      name: "testesa",
      price: 0,
      currency: "NGN",
      interval: "monthly",
      planGroup: "teateaesar",
      provider: "paystack",
      autoEnable: true,
      features: [],
    }),
    plan("money-man", {
      name: "money man",
      price: 100000,
      currency: "NGN",
      interval: "monthly",
      provider: "paystack",
      autoEnable: true,
      features: [sso.off(), supportCredits.credits(300, { reset: "monthly" })],
    }),
    plan("test-trial-polar2", {
      name: "test-trial-polar2",
      price: 1000,
      currency: "USD",
      interval: "monthly",
      trialDays: 1,
      provider: "polar",
      features: [
        thirdpen.limit(100, {
          reset: "5min",
          usageModel: "included",
          pricePerUnit: 20,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
        dearfutureself.limit(10, {
          reset: "5min",
          usageModel: "included",
          pricePerUnit: 30,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
      ],
    }),
    plan("test-trial-polar", {
      name: "test-trial-polar",
      price: 1000,
      currency: "USD",
      interval: "monthly",
      planGroup: "sales",
      trialDays: 3,
      provider: "polar",
      features: [supportCredits.credits(100, { reset: "monthly" })],
    }),
    plan("wanssoawe", {
      name: "wanssoawe",
      price: 2000,
      currency: "USD",
      interval: "monthly",
      planGroup: "support",
      provider: "dodopayments",
      features: [
        thirdpen.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
        dearfutureself.config({
          limit: null,
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("dry", {
      name: "dry",
      description: "a nice poor plan",
      price: 1400,
      currency: "USD",
      interval: "monthly",
      provider: "dodopayments",
      features: [
        supportCredits.credits(100, { reset: "5min", overage: "charge" }),
        thirdpen.config({
          limit: null,
          reset: "monthly",
          usageModel: "usage_based",
          pricePerUnit: 100,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
      ],
    }),
    plan("test-trial-dodod", {
      name: "test-trial-dodod",
      price: 10000,
      currency: "USD",
      interval: "monthly",
      trialDays: 2,
      provider: "dodopayments",
      features: [
        thirdpen.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
        supportCredits.credits(100, { reset: "monthly", overage: "charge" }),
        dearfutureself.limit(10, {
          reset: "5min",
          usageModel: "included",
          pricePerUnit: 200,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
      ],
    }),
    plan("test-trial-dodo-1", {
      name: "test-trial-dodo",
      price: 1000,
      currency: "USD",
      interval: "monthly",
      trialDays: 15,
      provider: "dodopayments",
      features: [supportCredits.credits(100, { reset: "monthly" })],
    }),
    plan("test-trial-dodo", {
      name: "test-trial-dodo",
      price: 1000,
      currency: "USD",
      interval: "monthly",
      trialDays: 3,
      provider: "dodopayments",
      features: [
        thirdpen.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("test-trial-stack", {
      name: "test-trial-stack",
      price: 100000,
      currency: "NGN",
      interval: "monthly",
      trialDays: 3,
      provider: "paystack",
      features: [
        thirdpenCredits.credits(100, { reset: "monthly" }),
        dearfutureself.config({
          limit: null,
          reset: "monthly",
          usageModel: "included",
          pricePerUnit: 300,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
      ],
    }),
    plan("masterxx", {
      name: "masterxx",
      price: 100000,
      currency: "USD",
      interval: "monthly",
      provider: "dodopayments",
      features: [supportCredits.credits(100, { reset: "5min" })],
    }),
    plan("teast", {
      name: "teast",
      price: 0,
      currency: "NGN",
      interval: "monthly",
      planGroup: "sales",
      autoEnable: true,
      features: [
        supportCredits.credits(100, { reset: "15min", overage: "charge" }),
      ],
    }),
    plan("mastert", {
      name: "mastert",
      price: 1000000,
      currency: "NGN",
      interval: "monthly",
      trialDays: 4,
      provider: "paystack",
      features: [
        dearfutureself.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
        apiRequests.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("masterx", {
      name: "masterx",
      price: 1000000,
      currency: "NGN",
      interval: "monthly",
      trialDays: 4,
      provider: "paystack",
      features: [
        apiRequests.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
        thirdpen.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("master2", {
      name: "master2",
      price: 10000,
      currency: "NGN",
      interval: "monthly",
      trialDays: 4,
      provider: "paystack",
      features: [
        apiRequests.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("master", {
      name: "master",
      price: 1000000,
      currency: "NGN",
      interval: "monthly",
      trialDays: 4,
      provider: "paystack",
      features: [
        apiRequests.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("credit-plan", {
      name: "Credit plan",
      price: 10000,
      currency: "NGN",
      interval: "monthly",
      features: [
        thirdpen.limit(10, {
          reset: "5min",
          usageModel: "included",
          pricePerUnit: 10000,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
        dearfutureself.limit(10, {
          reset: "5min",
          usageModel: "included",
          pricePerUnit: 10900,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
        dfs.config({
          limit: null,
          reset: "5min",
          usageModel: "usage_based",
          pricePerUnit: 1000,
          ratingModel: "package",
          billingUnits: 1,
          overage: "charge",
        }),
      ],
    }),
    plan("pro-plan", {
      name: "pro plan",
      price: 3000000,
      currency: "NGN",
      interval: "monthly",
      provider: "paystack",
      features: [
        thirdpen.limit(200, {
          reset: "5min",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
        apiRequests.limit(200, {
          reset: "5min",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    plan("basic", {
      name: "basic",
      price: 100000,
      currency: "NGN",
      interval: "monthly",
      provider: "paystack",
      features: [
        apiRequests.limit(100, {
          reset: "monthly",
          usageModel: "included",
          ratingModel: "package",
          billingUnits: 1,
        }),
      ],
    }),
    creditPack("extra-thirdpen-credits", {
      name: "extra thirdpen credits",
      credits: 100,
      price: 5000,
      currency: "NGN",
      creditSystem: "thirdpen-credits",
      provider: "paystack",
    }),
    creditPack("40-extra-xcredits", {
      name: "40 extra xcredits",
      credits: 100,
      price: 2,
      currency: "USD",
      creditSystem: "support-credits",
      provider: "dodopayments",
    }),
    creditPack("40-extra-creditssds", {
      name: "40 extra creditssds",
      credits: 100,
      price: 500,
      currency: "NGN",
      creditSystem: "support-credits",
    }),
  ],
});
